name: check

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  is-org-member:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.is-org-member.outputs.result }}
    steps:
      - name: Check if author is tiiuae member
        id: is-org-member
        uses: JamesSingleton/is-organization-member@1.0.1
        with:
          organization: tiiuae
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug
        shell: bash
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.repository: ${{ github.repository }}"
          echo "github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "github.actor: ${{ github.actor }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}"
          echo "is-org-member result: ${{ steps.is-org-member.outputs.result }}"

  # Authorization passes without approval if:
  # - The event is not a pull request (e.g. push to main)
  # - Pull request comes from another branch in the same repo
  # Otherwise, the workflow requires
  # manual approval from a maintainer with write permissions to continue
  authorize:
    needs: [is-org-member]
    environment: ${{
      ( github.event_name != 'pull_request_target' ||
        github.event.pull_request.head.repo.full_name == github.repository ||
        needs.is-org-member.outputs.result == 'true' )
      && 'internal' || 'external' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Auth OK"

  # Send a warning and fail this job if the workflow file was changed.
  # Rest of the workflow continues as normal but the job failure will grab author's attention.
  no-workflow-changes:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0

      - name: Check if workflow is modified
        id: workflow-changed
        uses: tj-actions/changed-files@v45.0.7
        with:
          files: .github/workflows/check.yml

      - name: Send warning
        run: |
          if [ "${{ steps.workflow-changed.outputs.any_changed }}" == "true" ]; then
            echo "::error::"\
                 "This change edits workflow file '.github/workflows/check.yml'."\
                 "Raising this error to notify that the workflow change will only take impact after merge."\
                 "Therefore, you need to manually test the change (perhaps in a forked repo) "\
                 "before merging to make sure the change does not break anything."

            exit 1
          fi

  run-checks:
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.READ_PRIVATE_REPO }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Nix flake check
        run: nix flake check
      - name: Nix run
        run: nix run .#hello-private

